import Head from 'next/head';
import { Flex } from '@chakra-ui/react';

import { HeroBody } from '@components/Hero/HeroBody';

export default function Home() {
  return (
    <Flex>
      <Head>
        <title>Borealis NFT Marketplace</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <HeroBody />
    </Flex>
  );
}
