import Head from 'next/head';
import { Text, Flex, Button } from '@chakra-ui/react';

export default function Home() {
  return (
    <Flex>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Text>Hello from chakra</Text>
      <Button>Click me</Button>
    </Flex>
  );
}
